#!/usr/bin/env bash
# lazy-zsh / install.sh
# Move from bash to zsh + oh-my-zsh in one go: plugins, history, aliases.
#
# Usage:
#   ./install.sh          install, keep your current default shell
#   ./install.sh --chsh   install and make zsh the default shell
#
# Safe to re-run. Undo everything with ./rollback.sh

set -euo pipefail

NAME="lazy-zsh"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/$NAME"
REPORT="$STATE_DIR/manual-steps.txt"
PACKAGES=(zsh git curl fzf python3)
TS="$(date +%Y%m%d-%H%M%S)"

DO_CHSH=0
for arg in "$@"; do
  case "$arg" in
    --chsh) DO_CHSH=1 ;;
    -h|--help) sed -n '2,9p' "$0"; exit 0 ;;
    *) echo "Unknown argument: $arg (see --help)" >&2; exit 1 ;;
  esac
done

if [[ $EUID -eq 0 ]]; then
  echo "Run it as your normal user, not root (sudo is used only for apt)." >&2
  exit 1
fi

log()  { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!\033[0m %s\n' "$*"; }

backup() {
  if [[ -e "$1" ]]; then
    cp -a "$1" "$1.bak.$TS"
    log "backup: $1 -> $1.bak.$TS"
  fi
}

clone_or_update() {
  local url="$1" dir="$2"
  if [[ -d "$dir/.git" ]]; then
    git -C "$dir" pull --ff-only --quiet && log "updated: $(basename "$dir")"
  else
    git clone --depth=1 --quiet "$url" "$dir" && log "cloned: $(basename "$dir")"
  fi
}

# Values recorded on the first run only, so rollback.sh knows the original state
state_once() { [[ -s "$STATE_DIR/$1" ]] || printf '%s\n' "$2" > "$STATE_DIR/$1"; }

mkdir -p "$STATE_DIR"
# An earlier install by an older version of this script left no state, but left markers
PREV_INSTALL=0
grep -qsE 'generated by (lazy-zsh|setup-zsh\.sh)' "$HOME/.zshrc" && PREV_INSTALL=1
if [[ -f "$HOME/.zsh_history.bash-imported" ]]; then
  state_once install_ts "$(stat -c %Y "$HOME/.zsh_history.bash-imported")"
else
  state_once install_ts "$(date +%s)"
fi
state_once original_shell  "$(getent passwd "$USER" | cut -d: -f7)"
state_once omz_preexisting "$([[ $PREV_INSTALL -eq 0 && -d $HOME/.oh-my-zsh ]] && echo yes || echo no)"
ZSHRC_EXISTED=0; [[ -e "$HOME/.zshrc" ]] && ZSHRC_EXISTED=1

# ---------------------------------------------------------------- 1. packages
if command -v apt-get >/dev/null 2>&1; then
  missing=()
  for p in "${PACKAGES[@]}"; do
    dpkg-query -W -f='${Status}' "$p" 2>/dev/null | grep -q 'install ok installed' || missing+=("$p")
  done
  if (( ${#missing[@]} )); then
    log "Installing: ${missing[*]} (sudo)"
    printf '%s\n' "${missing[@]}" >> "$STATE_DIR/packages_installed"
    sudo apt-get update -qq
    sudo apt-get install -y -qq "${missing[@]}"
  else
    log "Packages already installed: ${PACKAGES[*]}"
  fi
else
  for c in zsh git curl python3; do
    if ! command -v "$c" >/dev/null 2>&1; then
      echo "No apt-get here and '$c' is missing. Install zsh, git, curl, python3 (and fzf) yourself, then re-run." >&2
      exit 1
    fi
  done
  warn "No apt-get: using the zsh/git/curl/python3 you already have"
fi
ZSH_BIN="$(command -v zsh)"

# ---------------------------------------------------------------- 2. oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
if [[ -d "$ZSH/.git" ]]; then
  log "oh-my-zsh already installed, updating"
  git -C "$ZSH" pull --ff-only --quiet || warn "oh-my-zsh update failed, continuing"
else
  log "Installing oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" \
    "" --unattended --keep-zshrc --skip-chsh
fi

# ---------------------------------------------------------------- 3. external plugins
ZSH_CUSTOM_DIR="$ZSH/custom"
mkdir -p "$ZSH_CUSTOM_DIR/plugins"
clone_or_update https://github.com/zsh-users/zsh-autosuggestions     "$ZSH_CUSTOM_DIR/plugins/zsh-autosuggestions"
clone_or_update https://github.com/zsh-users/zsh-syntax-highlighting "$ZSH_CUSTOM_DIR/plugins/zsh-syntax-highlighting"
clone_or_update https://github.com/zsh-users/zsh-completions         "$ZSH_CUSTOM_DIR/plugins/zsh-completions"

# ---------------------------------------------------------------- 4. ~/.zshrc
# If there was no ~/.zshrc before this run, the file now there is the
# oh-my-zsh template: overwrite it without a backup.
[[ $ZSHRC_EXISTED -eq 1 ]] && backup "$HOME/.zshrc"
cat > "$HOME/.zshrc" <<'ZSHRC'
# ~/.zshrc - generated by lazy-zsh. Re-running install.sh overwrites it (with a backup).
# Put your own stuff into ~/.zshrc.local - it is loaded at the end and never touched.

# --- PATH. Must be set BEFORE oh-my-zsh: plugins like rust and uv
# --- call their tools on load to generate completions.
[[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"
typeset -U path PATH
path=("$HOME/.local/bin" "$HOME/bin" $path)

export ZSH="$HOME/.oh-my-zsh"
ZSH_CUSTOM="${ZSH_CUSTOM:-$ZSH/custom}"
ZSH_THEME="robbyrussell"

# zsh-completions: added to fpath, not to plugins (as its README says)
fpath+=("$ZSH_CUSTOM/plugins/zsh-completions/src")

# "plugin:command" - enabled only if the command is installed.
# "plugin:"        - always enabled. Missing plugins are skipped silently.
_lazy_plugins=(
  git:git gh:gh
  docker:docker docker-compose:docker kubectl:kubectl
  rust:cargo
  python:python3 uv:uv
  npm:npm
  aws:aws terraform:terraform
  fzf:fzf                   # Ctrl-R history search, Ctrl-T files, Alt-C dirs
  sudo:                     # Esc Esc adds sudo to the current/previous command
  extract:                  # x <archive>
  colored-man-pages:
  command-not-found:
  zsh-autosuggestions:
  zsh-syntax-highlighting:  # must stay last
)
plugins=()
for _e in $_lazy_plugins; do
  _p=${_e%%:*} _c=${_e#*:}
  [[ -n $_c ]] && (( ! $+commands[$_c] )) && continue
  [[ -d $ZSH/plugins/$_p || -d $ZSH_CUSTOM/plugins/$_p ]] && plugins+=($_p)
done
unset _e _p _c _lazy_plugins

ZSH_AUTOSUGGEST_STRATEGY=(history completion)

source "$ZSH/oh-my-zsh.sh"

# --- History. Set after oh-my-zsh, because its lib/history.zsh sets own defaults.
HISTFILE="$HOME/.zsh_history"
HISTSIZE=120000                # in memory; must be > SAVEHIST for HIST_EXPIRE_DUPS_FIRST
SAVEHIST=100000                # in file
setopt EXTENDED_HISTORY        # store start time and duration of each command
unsetopt SHARE_HISTORY         # each terminal tab keeps its own up-arrow history...
unsetopt INC_APPEND_HISTORY
setopt INC_APPEND_HISTORY_TIME # ...but every command is written to file right after it finishes
setopt HIST_IGNORE_SPACE       # " cmd" (leading space) is not saved - for secrets/tokens
setopt HIST_IGNORE_DUPS        # no consecutive duplicates
setopt HIST_EXPIRE_DUPS_FIRST  # when trimming, drop duplicates first
setopt HIST_FIND_NO_DUPS       # no duplicates when searching
setopt HIST_REDUCE_BLANKS      # trim extra spaces
setopt HIST_VERIFY             # !! and !$ are expanded into the line, not run immediately
# Want live sharing between tabs instead? Replace the 3 lines above with: setopt SHARE_HISTORY

# --- Aliases (loaded after oh-my-zsh, so yours win over plugin aliases)
[[ -f "$HOME/.bash_aliases" ]] && source "$HOME/.bash_aliases"
[[ -f "$HOME/.zsh_aliases"  ]] && source "$HOME/.zsh_aliases"

[[ -f "$HOME/.zshrc.local" ]] && source "$HOME/.zshrc.local"
ZSHRC
log "wrote ~/.zshrc"

# ---------------------------------------------------------------- 5. ~/.zprofile
# zsh does not read ~/.profile, but on Debian/Ubuntu that is where ~/.local/bin
# and the cargo env get into PATH. Without this, login zsh (and the desktop
# session after chsh) would lose them.
if ! grep -qsE '# added by (lazy-zsh|setup-zsh\.sh)' "$HOME/.zprofile"; then
  backup "$HOME/.zprofile"
  cat >> "$HOME/.zprofile" <<'ZPROFILE'
# added by lazy-zsh: load ~/.profile like bash does
[[ -f "$HOME/.profile" ]] && emulate sh -c '. "$HOME/.profile"'
ZPROFILE
  log "updated ~/.zprofile"
fi

# ---------------------------------------------------------------- 6. aliases
# ~/.bash_aliases is loaded as is from ~/.zshrc (single source of truth).
# Aliases written directly in ~/.bashrc are copied to ~/.zsh_aliases.
if [[ -f "$HOME/.bashrc" ]]; then
  ALIASES="$(grep -E '^[[:space:]]*alias[[:space:]]+' "$HOME/.bashrc" | sed -E 's/^[[:space:]]+//' || true)"
  if [[ -n "$ALIASES" ]]; then
    backup "$HOME/.zsh_aliases"
    {
      echo "# copied from ~/.bashrc by lazy-zsh on $TS"
      echo "$ALIASES"
    } > "$HOME/.zsh_aliases"
    log "copied $(echo "$ALIASES" | wc -l) aliases from ~/.bashrc -> ~/.zsh_aliases"
  fi
fi

# ---------------------------------------------------------------- 7. history
MARKER="$HOME/.zsh_history.bash-imported"
if [[ -f "$MARKER" ]]; then
  log "bash history was imported earlier, skipping"
elif [[ -s "$HOME/.bash_history" ]]; then
  backup "$HOME/.zsh_history"
  python3 - "$HOME/.bash_history" "$HOME/.zsh_history" <<'PY'
import os, re, sys

src, dst = sys.argv[1], sys.argv[2]
lines = open(src, "rb").read().split(b"\n")

# bash with HISTTIMEFORMAT writes "#<epoch>" before each command
entries, ts = [], None
for line in lines:
    m = re.fullmatch(rb"#(\d{9,11})", line)
    if m:
        ts = int(m.group(1))
        continue
    if not line.strip():
        continue
    entries.append((ts, line))
    ts = None

# no timestamps -> fake ascending ones ending at the file mtime (keeps order)
base = int(os.path.getmtime(src)) - len(entries)

def metafy(b):
    # zsh stores history "metafied": bytes 0x83..0xA2 (and NUL) are written
    # as 0x83 followed by byte^0x20. UTF-8 text (Cyrillic etc.) hits this
    # range, so a plain copy would be read back broken.
    out = bytearray()
    for c in b:
        if c == 0 or 0x83 <= c <= 0xA2:
            out += bytes((0x83, c ^ 0x20))
        else:
            out.append(c)
    return bytes(out)

new = bytearray()
for i, (t, cmd) in enumerate(entries):
    new += b": %d:0;" % (t if t is not None else base + i) + metafy(cmd) + b"\n"

old = open(dst, "rb").read() if os.path.exists(dst) else b""
tmp = dst + ".tmp"
with open(tmp, "wb") as f:
    f.write(bytes(new) + old)   # bash history first, existing zsh history after
os.chmod(tmp, 0o600)
os.replace(tmp, dst)
print(f"imported {len(entries)} commands")
PY
  touch "$MARKER"
  log "bash history imported into ~/.zsh_history"
else
  warn "~/.bash_history is empty or missing, nothing to import"
fi

# ---------------------------------------------------------------- 8. default shell
if [[ $DO_CHSH -eq 1 ]]; then
  if [[ "$(getent passwd "$USER" | cut -d: -f7)" != "$ZSH_BIN" ]]; then
    log "Changing default shell to $ZSH_BIN (your password will be asked)"
    chsh -s "$ZSH_BIN"
  else
    log "zsh is already the default shell"
  fi
fi

# ---------------------------------------------------------------- 9. manual steps report
python3 - "$ZSH_BIN" "$(getent passwd "$USER" | cut -d: -f7)" "${SHELL:-}" > "$REPORT" <<'PY'
import glob, os, re, sys

zsh_bin, login_shell, session_shell = sys.argv[1:4]
HOME = os.path.expanduser("~")

def short(p):
    return "~" + p[len(HOME):] if p.startswith(HOME) else p

def read(p):
    try:
        with open(p, encoding="utf-8", errors="replace") as f:
            return f.read().splitlines()
    except OSError:
        return None

# --- split a shell file into top-level statements (functions, if-blocks, lines)
QUOTED = re.compile(r"'[^']*'|\"(?:\\.|[^\"\\])*\"")
OPEN = re.compile(r"(?:^|[\s;&|(])(if|case|for|while|until|select|\{)(?=$|[\s;])")
CLOSE = re.compile(r"(?:^|[\s;&|])(fi|esac|done|\})(?=$|[\s;&|)])")

def code_of(block):
    return [l.strip() for l in block if l.strip() and not l.strip().startswith("#")]

def blocks(lines):
    out, cur, depth, start = [], [], 0, 0
    for n, line in enumerate(lines, 1):
        s = line.strip()
        if not cur and (not s or s.startswith("#")):
            continue
        if not cur:
            start = n
        cur.append(line)
        if s and not s.startswith("#"):
            code = QUOTED.sub("''", s)
            depth += len(OPEN.findall(code)) - len(CLOSE.findall(code))
        if depth <= 0 and not s.endswith("\\"):
            out.append((start, n, code_of(cur)))
            cur, depth = [], 0
    if cur:
        out.append((start, len(lines), code_of(cur)))
    return [b for b in out if b[2]]

BASH_INIT = re.compile(r"(shell-integration-path|init|hook|completion|activate)\s+bash\b|--shell[= ]bash\b")
FUNC = re.compile(r"^(?:function\s+([\w.:-]+)|([\w.:-]+)\s*\(\s*\))")

def classify(code, target):
    text, first = "\n".join(code), code[0]
    if all(re.match(r"alias\s", l) for l in code):
        return "auto", f"{len(code)} alias(es)"
    if len(code) <= 3:
        if ".cargo/env" in text:      return "auto", "cargo env"
        if ".local/bin/env" in text:  return "auto", "~/.local/bin/env (uv)"
        if ".bash_aliases" in text:   return "auto", "~/.bash_aliases"
    if BASH_INIT.search(text):
        return "manual", f"bash-specific init. Copy it to {target} and replace 'bash' with 'zsh'."
    if "bash_completion" in text or re.search(r"^(complete|compgen)\s", text, re.M):
        return "skip", "bash completion. Not needed: zsh has its own."
    m = FUNC.match(first)
    if m:
        return "manual", f"function {m.group(1) or m.group(2)}. Usually works in zsh as is: copy it to {target}."
    if re.search(r"^(shopt|bind)\s|PROMPT_COMMAND|^PS[12]=", text, re.M):
        return "skip", "bash-only setting (shopt/bind/prompt). zsh and oh-my-zsh cover this."
    if re.match(r"(export\s+)?HIST", first):
        return "skip", "bash history setting. zsh history is already set up in ~/.zshrc."
    if re.search(r"\bPATH=", text):
        return "manual", f"PATH change. Copy it to {target}, the same syntax works in zsh."
    if re.match(r"(\\?\.|source)\s", first):
        return "manual", f"loads a file. Check that the file is not bash-only, then copy the line to {target}."
    if re.match(r"(export\s+)?[A-Za-z_]\w*=", first):
        return "manual", f"variable. Copy it to {target} as is."
    if first.startswith("eval"):
        return "manual", f"eval. Check it for bash-specific parts, then copy it to {target}."
    return "manual", f"custom code. Review it and copy it to {target} if you still need it."

manual, skipped, auto, terminals = [], [], [], []

def scan(path, skel_path, target, ignore=None):
    lines = read(path)
    if lines is None:
        return
    skel = {tuple(c) for _, _, c in blocks(read(skel_path) or [])} if skel_path else set()
    for s, e, code in blocks(lines):
        if tuple(code) in skel:
            continue                       # untouched distro default
        if ignore and ignore.search("\n".join(code)) and len(code) <= 3:
            continue
        kind, hint = classify(code, target)
        loc = f"{short(path)}:{s}" + (f"-{e}" if e != s else "")
        if kind == "auto":
            auto.append(hint)
        else:
            (manual if kind == "manual" else skipped).append((loc, code, hint))

has_skel = os.path.exists("/etc/skel/.bashrc")
scan(HOME + "/.bashrc", "/etc/skel/.bashrc" if has_skel else None, "~/.zshrc.local")
for f in (".bash_profile", ".bash_login"):
    # zsh reads neither; usual content just loads ~/.bashrc or ~/.profile
    scan(f"{HOME}/{f}", None, "~/.zprofile", re.compile(r"\.(bashrc|profile)\b"))

for n, l in enumerate(read(HOME + "/.bash_aliases") or [], 1):
    if re.match(r"\s*(shopt|bind|complete|compgen)\s|\s*export\s+-f\b", l):
        manual.append((f"~/.bash_aliases:{n}", [l.strip()],
                       "bash-only line in a file zsh also loads. Move it out, or wrap it in: "
                       "if [ -n \"$BASH_VERSION\" ]; then ... fi"))

# --- terminals that start bash explicitly, whatever the default shell is
for f in (HOME + "/.wezterm.lua", HOME + "/.config/wezterm/wezterm.lua"):
    for n, l in enumerate(read(f) or [], 1):
        if "default_prog" in l and "bash" in l and not l.strip().startswith("--"):
            terminals.append((f"{short(f)}:{n}", [l.strip()],
                              f"WezTerm starts bash. Change it to: config.default_prog = {{ '{zsh_bin}', '-l' }} or delete the line."))
for f in sorted(glob.glob(HOME + "/.local/share/konsole/*.profile")):
    for n, l in enumerate(read(f) or [], 1):
        if l.startswith("Command=") and "bash" in l:
            terminals.append((f"{short(f)}:{n}", [l.strip()],
                              f"Konsole profile starts bash. Settings -> Edit Current Profile -> Command: {zsh_bin}"))
for f in sorted(glob.glob(HOME + "/.config/*/User/settings.json")):
    for n, l in enumerate(read(f) or [], 1):
        if re.search(r'"terminal\.integrated\.defaultProfile\.linux"\s*:\s*"bash"', l):
            terminals.append((f"{short(f)}:{n}", [l.strip()],
                              f"{f.split('/')[-3]} terminal uses bash. Set this value to \"zsh\"."))

# --- print
def show(title, items):
    print(title)
    print("-" * len(title))
    for loc, code, hint in items:
        print(loc)
        for l in (code if len(code) <= 3 else code[:2]):
            print("    " + l)
        if len(code) > 3:
            print(f"    ... ({len(code)} lines)")
        print("  -> " + hint)
        print()

print()
if manual:
    show("Move by hand (not migrated automatically)", manual)
if terminals:
    show("Terminals that still start bash", terminals)
if not login_shell.endswith("zsh"):
    print("Default shell")
    print("-------------")
    print(f"Still {login_shell}. Re-run with --chsh, or set zsh only in your terminal,")
    print(f"e.g. WezTerm: config.default_prog = {{ '{zsh_bin}', '-l' }}")
    print()
elif not session_shell.endswith("zsh"):
    print("Default shell")
    print("-------------")
    print("zsh is the default shell now. Log out of your desktop session and back in:")
    print("closing the terminal is not enough, the shell is picked up at login.")
    print()
if skipped:
    show("Not needed in zsh", skipped)
if not manual and not terminals:
    print("Nothing to move by hand.")
    print()
n_alias = sum(1 for l in read(HOME + "/.bashrc") or [] if re.match(r"\s*alias\s", l))
done = ["bash history", "~/.profile (via ~/.zprofile)"]
if n_alias:
    done.append(f"{n_alias} aliases from ~/.bashrc")
if os.path.exists(HOME + "/.bash_aliases"):
    done.append("~/.bash_aliases (loaded as is)")
done += sorted(set(a for a in auto if "alias" not in a))
print("Migrated automatically: " + ", ".join(done))
if not has_skel:
    print("(no /etc/skel/.bashrc to compare with, so distro defaults may be listed above)")
PY
cat "$REPORT"
echo "This report is saved to: $REPORT"

# ---------------------------------------------------------------- 10. tips
cat <<'TIPS'

Quick tips
----------
  type a few letters      grey suggestion from history: Right arrow or End accepts it
  prefix + Up arrow       cycles only through commands starting with that prefix
  Ctrl-R                  fuzzy search in the whole history (Ctrl-T files, Alt-C dirs)
  Esc Esc                 put sudo in front of the current or last command
  x file.tar.gz           extract any archive
  " cmd"                  leading space = not saved to history (tokens, passwords)
  alias | grep git        git shortcuts from the git plugin: gst, gco, gp, glog, ...
  omz update              update oh-my-zsh (re-run install.sh to update the rest)
  ~/.zshrc.local          your own PATH, functions, exports; never overwritten
  ZSH_THEME in ~/.zshrc   change the prompt theme (ls ~/.oh-my-zsh/themes)
  ./rollback.sh           undo everything and go back to bash

Open a new terminal tab, or run: exec zsh -l
TIPS
